created dashboards controllers
AscariA10/TaskPro_API pull request #1
Opened 2023-06-22 21:29 UTC by Dudaeff

2023-06-22 21:29 UTC, Dudaeff commented on models/dasboards.js
> +    // owner: {
це на майбутнє

2023-06-23 14:49 UTC, AscariA10 requested changes

2023-06-23 14:49 UTC, AscariA10 commented on models/dasboards.js
> +    // owner: {
це я сьогодні прописав

2023-06-23 14:49 UTC, AscariA10 commented on controllers/dasboards.js
> +const Board = require("../models/dasboards");
models/dashboard

2023-06-23 14:49 UTC, AscariA10 commented on controllers/dasboards.js
> +const Board = require("../models/dasboards");
Board => Dashboard

2023-06-23 14:49 UTC, AscariA10 commented on controllers/dasboards.js
> +  const result = await Board.findByIdAndRemove(boardId);
boardId в ДБ немає, або достаєш _id, або (boardId: _id)

2023-06-23 16:18 UTC, AscariA10 approved these changes
Поки що приймаю, але якщо будуть питання то відправлю на доопрацювання

2023-06-23 16:18 UTC, merged